
- match: http_requests_total
  interval: 15s
  by:
  - span_name
  - status_code
  outputs:
  - total
  output_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      regex: "(.+):.+"
      replacement: "agg_http_requests_total"

- match: http_requests_duration_bucket
  interval: 15s
  by:
  - span_name
  - status_code
  - le
  outputs:
  - total
  output_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      regex: "(.+):.+"
      replacement: "agg_http_requests_duration_bucket"


- match: http_requests_duration_sum
  interval: 15s
  by:
  - span_name
  - status_code
  outputs:
  - total
  output_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      regex: "(.+):.+"
      replacement: "agg_http_requests_duration_sum"

- match: http_requests_duration_count
  interval: 15s
  by:
  - span_name
  - status_code
  outputs:
  - total
  output_relabel_configs:
    - source_labels: [__name__]
      target_label: __name__
      regex: "(.+):.+"
      replacement: "agg_http_requests_duration_count"
